---
title: "About"
output: html_document
---

### Background

While the COVID-19 outbreak was reported to first originate from Wuhan, China, it has been declared as a
Public Health Emergency of International Concern (PHEIC) on 30 January 2020 by WHO, and it has spread to over 180 countries. As the disease spreads around the globe, it has evolved into a world-wide pandemic, endangering the state of global public health and becoming a serious threat to the global community. To combat and prevent the spread of the disease, all individuals should be well- informed of the rapidly changing state of COVID-19. In the attempt of achieving this goal, a COVID-19 real-time analytical tracker has been built to provide the latest status of the disease and relevant analytical insights. The real-time tracker is designed to cater to the general audience without advanced statistical aptitude. It aims to communicate insights through various straightforward and concise data visualizations that are supported by sound statistical foundations and reliable data sources. 

### Related Work

The GitHub repository of the project can be accessed [here](https://github.com/peterljw/COVID-19-Real-Time-Tracker). For more details of the content and methodologies behind the making of this tracker, please refer to [this paper](https://github.com/peterljw/COVID-19-Real-Time-Tracker). The paper aims to discuss the major methodologies which are utilized to generate the insights displayed on the tracker, which include real-time data retrieval, normalization techniques, ARIMA time-series forecasting, hypothesis testing, and penalized logistic regression models. In addition to introducing the details and motivations of the utilized methodologies, the paper also highlights some key findings that have been derived in regard to COVID-19 using the methodologies.

### About me

I am a data enthusiast and a graduate student from UCLA. Please feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/peterljw/).

