---
title: "About"
output: html_document
---

### Background

While the COVID-19 outbreak was reported to first originate from Wuhan, China, it has been declared as a Public Health Emergency of International Concern (PHEIC) on 30 January 2020 by WHO, and it has spread to over 180 countries. As the disease spreads around the globe, it has evolved into a worldwide pandemic, endangering the state of global public health and becoming a serious threat to the global community. To combat and prevent the spread of the disease, all individuals should be well-informed of the rapidly changing state of COVID-19. In the attempt of achieving this goal, a COVID-19 real-time analytical tracker has been built to provide the latest status of the disease and relevant analytical insights. The real-time tracker is designed to cater to the general audience who desires to learn more about the state of COVID-19. It aims to communicate insights through various straightforward and concise data visualizations that are supported by sound statistical foundations and reliable data sources. The GitHub repository of the project can be accessed [here](https://github.com/peterljw/COVID-19-Real-Time-Tracker).


### About me

I am a data enthusiast and I enjoy making different data applications. Please feel free to check out more of my projects on my [GitHub]((https://github.com/peterljw/) and connect with me on [LinkedIn](https://www.linkedin.com/in/jiaweilong/).

